In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from pathlib import Path
import os

In [2]:
CURRENT_DIRECTORY =  os.getcwd()
SRC_DIRECTORY = Path(CURRENT_DIRECTORY).parents[1]
print(SRC_DIRECTORY)

BASE_DATASET_PATH = Path(SRC_DIRECTORY).parents[0]
BASE_DATASET_PATH = BASE_DATASET_PATH / "datasets"
print(BASE_DATASET_PATH)

/Users/yitong/Desktop/Uni_Skool/Y3 Internship SingHealth/code/Mobile-AED-Study/src
/Users/yitong/Desktop/Uni_Skool/Y3 Internship SingHealth/code/Mobile-AED-Study/datasets

In [7]:
# get subzone data with their corresponding areas in km^2
def get_subzone_data(year: int):
    """
    Args
    ------
    year: int
        year of the subzones you want (2019, 2014, 2008)

    Returns
    ------
    Subzone dataframe containing the subzone names, planning area names and areas of points of interest.
    """

    year = str(year)

    subzones_filepath = Path(BASE_DATASET_PATH / f"singapore_data/data_gov/masterplan_{year}/subzone_boundary_{year}.gpkg")
    subzones_gpd = gpd.read_file(subzones_filepath)
    subzones_gpd = subzones_gpd.map(lambda s: s.lower() if isinstance(s, str) else s)
    # lower() the column names of subzones_gpd
    subzones_gpd.columns = subzones_gpd.columns.str.lower()

    # there is no landuse data found for 2008 masterplan, 
    # so not able to merge with the subzone_classification file obtained from extracting_landuse_type.ipynb
    if year == "2008":
        return subzones_gpd

    subzones_filepath = Path(BASE_DATASET_PATH / f"singapore_data/data_gov/masterplan_{year}/subzone_classifications_{year}.csv")
    subzones_csv = pd.read_csv(subzones_filepath)
    subzones_csv = subzones_csv.map(lambda s: s.lower() if isinstance(s, str) else s)

    subzones_with_geom = subzones_csv.merge(
        subzones_gpd[["subzone_n", "geometry"]],
        on = "subzone_n",
        how = "left"
    )

    missing_count = subzones_with_geom[subzones_with_geom.columns[-1]].isna().sum()
    if missing_count > 0:
        print(f"Warning: {missing_count} subzones did not find a match in the CSV.")

    return subzones_with_geom

def convert_to_geodataframe(df):
    if not isinstance(df, gpd.GeoDataFrame):
        df = gpd.GeoDataFrame(df, geometry='geometry')

    # ensure the original data has the correct starting CRS (WGS84)
    # (Only needed if it isn't already set; usually .gpkg files have this metadata)
    if df.crs is None:
        df.set_crs(epsg=4326, inplace=True)

    # transform the entire GeoDataFrame to SVY21 (Meters)
    df_meters = df.to_crs(epsg=3414)

    return df_meters

In [4]:
def get_education_data(year: int):

    year = str(year)

    education_filepath = Path(BASE_DATASET_PATH / f"singapore_data/cleaned_data/education_combined.xlsx")
    education_df = pd.read_excel(education_filepath, sheet_name = f"{year}")

    education_df = education_df.rename(columns = {
        "planning_area": "pln_area_n"
    })

    return education_df

In [8]:
subzone_df = get_subzone_data(2008)
subzone_df = convert_to_geodataframe(subzone_df)
subzone_df

,objectid,subzone_no,subzone_n,subzone_c,ca_ind,pln_area_n,pln_area_c,region_n,region_c,inc_crc,fmel_upd_d,x_addr,y_addr,shape_leng,shape_area,geometry
0,1,1,woodlands regional centre,wdsz01,n,woodlands,wd,north region,nr,8877712517deec59,2016-05-11,22571.2094,46698.8735,3254.343275,5.956521e+05,"MULTIPOLYGON (((22629.486 46980.246, 22683.012..."
1,2,1,kranji,sksz01,n,sungei kadut,sk,north region,nr,de75f42ec0f86b2b,2016-05-11,19767.5129,46226.3625,7906.523525,3.654121e+06,"MULTIPOLYGON (((20329.947 47234.988, 20333.366..."
2,3,2,turf club,sksz02,n,sungei kadut,sk,north region,nr,5d555db858522781,2016-05-11,20234.1723,44507.1299,7677.244752,3.290816e+06,"MULTIPOLYGON (((21094.367 44815.121, 21099.854..."
3,4,7,nee soon,yssz07,n,yishun,ys,north region,nr,d5436ffe80750d15,2016-05-11,25922.1222,43260.2558,7074.178844,2.209311e+06,"MULTIPOLYGON (((26860.555 43913.328, 26839.719..."
4,5,9,yishun west,yssz09,n,yishun,ys,north region,nr,6cc6926ff0495d89,2016-05-11,27743.2683,45873.5516,5313.554643,1.517705e+06,"MULTIPOLYGON (((28228.609 45792.488, 28223.039..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,307,2,sungei serangoon west,sesz02,n,sengkang,se,north-east region,ner,dd1f0c466afa1e91,2016-05-11,35978.7574,41060.2561,6305.618929,1.572812e+06,"MULTIPOLYGON (((37009.969 40867.361, 37011.087..."
307,308,7,sungei serangoon,hgsz07,n,hougang,hg,north-east region,ner,fa12e3e0162969b6,2016-05-11,35870.2559,39071.4374,5788.601229,1.333531e+06,"MULTIPOLYGON (((36538.391 39761.352, 36517.439..."
308,309,1,hougang central,hgsz01,n,hougang,hg,north-east region,ner,3e946e53a7bafde2,2016-05-11,35042.8392,39344.8093,6868.798253,2.291220e+06,"MULTIPOLYGON (((35948.803 40264.817, 35951.927..."
309,310,3,changi west,chsz03,n,changi,ch,east region,er,64b23a491470d534,2016-05-11,44092.2139,38928.4138,14919.112423,4.849019e+06,"MULTIPOLYGON (((45347.86 41116.219, 45350.666 ..."
310,311,2,changi airport,chsz02,n,changi,ch,east region,er,cc6eebdd760c6808,2016-05-11,46661.9033,36599.7731,28150.907298,3.509552e+07,"MULTIPOLYGON (((50293.959 38052.658, 50261.722..."

In [5]:
education_df = get_education_data(2010)
education_df

,pln_area_n,total,no_qualification,pri,lower_sec,sec,post_sec_(non-tertiary),poly_diploma,professional_qualification_&_other_diploma,uni
0,total,2779524,424443,193181,282523,526359,307562,250213,161144,634098
1,ang mo kio,140471,28602,11235,15798,24569,13592,11731,7162,27783
2,bedok,222290,33901,14542,22563,41999,24186,17438,12986,54675
3,bishan,68301,7486,3189,5256,12913,7417,5384,4621,22035
4,bukit batok,106726,14604,6677,9735,19178,11781,10103,6282,28365
5,bukit merah,123946,28790,10278,13063,20455,10390,8935,5841,26196
6,bukit panjang,93135,14065,7036,9782,17642,11741,9701,5162,18007
7,bukit timah,49294,2487,891,1869,5346,4865,2862,3400,27575
8,changi,1630,151,77,144,413,273,273,125,174
9,choa chu kang,122694,15609,8707,12562,24567,14923,13239,7377,25711
10,clementi,69660,11044,4651,6776,11794,6565,5462,3955,19413
11,downtown core,3104,547,248,243,450,262,185,159,1010
12,geylang,93036,18653,7691,10382,17150,9774,7301,4723,17361
13,hougang,159847,26236,11679,17958,32604,17289,14922,8793,30366
14,jurong east,65983,10488,4919,6777,12647,7260,6393,3671,13827
15,jurong west,194853,30025,15505,22365,36775,24904,19117,11482,34678
16,kallang,78049,16966,6792,8317,12938,6944,5543,3859,16689
17,mandai,1186,137,19,110,227,124,113,56,399
18,marine parade,34601,4186,1455,2922,5860,3649,2204,2148,12178
19,newton,4289,93,62,72,444,368,128,333,2789
20,novena,34740,4823,1910,2646,5526,3432,2184,2151,12068
21,outram,14253,4189,1824,1605,2311,921,865,446,2090
22,pasir ris,91039,7639,4557,7972,21288,12746,9798,6329,20710
23,punggol,43112,4408,2205,3471,8096,4778,5203,3309,11642
24,queenstown,74445,13711,5277,6944,12517,6365,5436,4067,20128
25,river valley,5932,216,122,273,620,481,252,391,3578
26,rochor,11847,2378,1150,1412,2045,1111,894,552,2304
27,sembawang,51545,5961,3253,4851,9420,6175,6067,3475,12343
28,sengkang,119907,15108,7558,11843,22461,13043,12868,7792,29235
29,serangoon,92439,11888,5587,8370,17608,9673,8141,5827,25345
30,singapore river,1308,37,0,26,116,131,51,36,910
31,tampines,188601,25205,12195,19487,42260,23514,18939,10891,36110
32,tanglin,12262,316,72,349,1141,1036,495,867,7985
33,toa payoh,96521,18776,7325,10158,18270,9370,7847,5261,19515
34,woodlands,170639,23796,12987,20342,36247,22387,17412,9823,27645
35,yishun,135678,21804,11475,16018,28269,15916,12601,7671,21924
36,others,2163,114,32,62,190,176,128,123,1337

In [ ]:
if not isinstance(subzone_df, gpd.GeoDataFrame):
    subzone_df = gpd.GeoDataFrame(subzone_df, geometry='geometry')

# transform the entire GeoDataFrame to SVY21 (Meters)
subzone_df_meters = subzone_df.to_crs(epsg=3414)

# calculate area
subzone_df['area_sqm'] = subzone_df_meters.geometry.area
subzone_df['area_sqkm'] = subzone_df['area_sqm'] / 1_000_000

pln_area_summary = subzone_df.groupby('pln_area_n')['area_sqkm'].sum().reset_index()
pln_area_summary = pln_area_summary.rename(columns={'area_sqkm': 'total_pln_area_sqkm'})

display(pln_area_summary.head())

                 pln_area_n  total_pln_area_sqkm
0                ang mo kio            13.938855
1                     bedok            21.731366
2                    bishan             7.623878
3                  boon lay             8.276807
4               bukit batok            11.130249
5               bukit merah            14.472307
6             bukit panjang             8.989134
7               bukit timah            17.529373
8   central water catchment            37.148805
9                    changi            40.940481
10               changi bay             1.849742
11            choa chu kang             6.113854
12                 clementi             9.513276
13            downtown core             4.472992
14                  geylang             9.642871
15                  hougang            13.928909
16              jurong east            17.857763
17              jurong west            14.688294
18                  kallang             9.168911
19             lim chu kang            17.492753
20                   mandai            11.766890
21              marina east             1.830733
22             marina south             1.630477
23            marine parade             6.136327
24                   museum             0.830288
25                   newton             2.068722
26    north eastern islands            67.250248
27                   novena             8.979561
28                  orchard             0.957525
29                   outram             1.373190
30                pasir ris            15.810712
31               paya lebar            11.689999
32                  pioneer            12.217136
33                  punggol             9.379969
34               queenstown            21.508739
35             river valley             1.474949
36                   rochor             1.614581
37                  seletar            10.861523
38                sembawang            12.635429
39                 sengkang            10.593137
40                serangoon            10.102016
41                  simpang             7.833401
42          singapore river             0.957260
43         southern islands             7.136612
44             straits view             1.129284
45             sungei kadut            17.629112
46                 tampines            20.913646
47                  tanglin             7.624715
48                   tengah             7.401786
49                toa payoh             8.167172
50                     tuas            40.097152
51          western islands            45.610770
52  western water catchment            69.708075
53                woodlands            13.612386
54                   yishun            21.578928

#### As I do not have enough information on resident's highest education level, I would not be able to perform interpolation on it
- Highest education level on the subzone level could not be found in data.gov
- Annual changes of higest education level could not be found too.